import { StyleSheet } from "@react-pdf/renderer"
import { PDF_FONT_DISPLAY, PDF_FONT_TEXT } from "./register-sf-pro-pdf-fonts"

export const BRAND = {
  azul: "#1B4A77",
  verde: "#40A74D",
  gris: "#6B7280",
  grisClaro: "#F3F4F6",
  borde: "#E5E7EB",
  texto: "#111827",
  blanco: "#FFFFFF",
}

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingBottom: 36,
    paddingHorizontal: 32,
    fontFamily: PDF_FONT_TEXT,
    fontSize: 8,
    color: BRAND.texto,
    backgroundColor: BRAND.blanco,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  title: {
    fontSize: 16,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.azul,
    marginTop: 4,
  },
  fecha: {
    fontSize: 8,
    color: BRAND.gris,
    textAlign: "right",
  },
  clienteBox: {
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: BRAND.borde,
  },
  clienteText: {
    fontSize: 8,
    color: BRAND.gris,
    lineHeight: 1.4,
  },
  sectionTitle: {
    fontSize: 9,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.azul,
    marginBottom: 6,
    marginTop: 8,
    textTransform: "uppercase",
  },
  twoCols: {
    flexDirection: "row",
    gap: 10,
  },
  col: {
    flex: 1,
  },
  block: {
    borderWidth: 1,
    borderColor: BRAND.borde,
    borderRadius: 6,
    padding: 8,
    marginBottom: 6,
  },
  blockHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: BRAND.borde,
  },
  blockHeaderLabel: {
    fontSize: 7,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.azul,
    textTransform: "uppercase",
  },
  blockTarifaName: {
    fontSize: 7,
    color: BRAND.texto,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
  },
  logo: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: BRAND.grisClaro,
    paddingVertical: 3,
    paddingHorizontal: 4,
    borderRadius: 3,
    marginBottom: 2,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 2,
    paddingHorizontal: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: BRAND.borde,
  },
  th: {
    fontSize: 6.5,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.gris,
    textTransform: "uppercase",
  },
  td: {
    fontSize: 7,
    color: BRAND.texto,
  },
  colPeriod: { width: "18%" },
  colMid: { width: "32%", textAlign: "right" },
  colPrice: { width: "25%", textAlign: "right" },
  colTotal: { width: "25%", textAlign: "right" },
  colConcept: { width: "45%" },
  colConceptPrice: { width: "27%", textAlign: "right" },
  colConceptTotal: { width: "28%", textAlign: "right" },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: BRAND.borde,
  },
  totalLabel: {
    fontSize: 7.5,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
  },
  invoiceCardsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 10,
    marginBottom: 14,
  },
  invoiceCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: BRAND.borde,
    borderRadius: 8,
    padding: 10,
    backgroundColor: BRAND.blanco,
  },
  invoiceCardPropuesta: {
    borderColor: BRAND.verde,
  },
  invoiceLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  invoiceTotal: {
    fontSize: 14,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    marginTop: 4,
  },
  invoiceTotalVerde: {
    color: BRAND.verde,
  },
  savingsBanner: {
    backgroundColor: BRAND.verde,
    borderRadius: 10,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  savingsTitle: {
    fontSize: 18,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.blanco,
  },
  savingsSubtitle: {
    fontSize: 8,
    color: BRAND.blanco,
    opacity: 0.9,
    marginTop: 4,
  },
  savingsCards: {
    flexDirection: "row",
    gap: 10,
  },
  savingsCard: {
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 8,
    padding: 10,
    minWidth: 120,
  },
  savingsCardHighlight: {
    backgroundColor: BRAND.blanco,
    minWidth: 130,
  },
  savingsCardLabel: {
    fontSize: 6.5,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.gris,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  savingsCardValue: {
    fontSize: 16,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.texto,
  },
  savingsCardValueLarge: {
    fontSize: 20,
  },
  conjuntoLayout: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    marginTop: 4,
  },
  conjuntoLeft: {
    width: "46%",
  },
  conjuntoRight: {
    flex: 1,
  },
  conjuntoHeroCard: {
    backgroundColor: BRAND.verde,
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
  },
  conjuntoHeroLabel: {
    fontSize: 7,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.blanco,
    textTransform: "uppercase",
    opacity: 0.9,
  },
  conjuntoHeroValue: {
    fontSize: 24,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.blanco,
    marginTop: 4,
  },
  conjuntoHeroHelper: {
    fontSize: 7,
    color: BRAND.blanco,
    opacity: 0.92,
    marginTop: 4,
    lineHeight: 1.35,
  },
  conjuntoTotalCard: {
    borderWidth: 1,
    borderColor: BRAND.borde,
    borderRadius: 8,
    padding: 9,
    marginBottom: 7,
  },
  conjuntoTotalCardHighlight: {
    borderColor: BRAND.verde,
  },
  conjuntoTotalLabel: {
    fontSize: 6.5,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.gris,
    textTransform: "uppercase",
  },
  conjuntoTotalValue: {
    fontSize: 13,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.texto,
    marginTop: 3,
  },
  conjuntoTotalValueHighlight: {
    color: BRAND.verde,
  },
  conjuntoTotalHelper: {
    fontSize: 6.5,
    color: BRAND.gris,
    marginTop: 2,
    lineHeight: 1.3,
  },
  cupsListHeader: {
    flexDirection: "row",
    backgroundColor: BRAND.grisClaro,
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 3,
    marginBottom: 2,
  },
  cupsListTh: {
    fontSize: 6.5,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.gris,
    textTransform: "uppercase",
  },
  cupsListRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: BRAND.borde,
  },
  cupsCol: { flex: 1 },
  cupsColAhorro: { width: 78, textAlign: "right" },
  cupsCode: {
    fontSize: 7,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.texto,
  },
  cupsCliente: {
    fontSize: 6.5,
    color: BRAND.gris,
    marginTop: 1,
  },
  cupsAhorro: {
    fontSize: 8.5,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.verde,
    textAlign: "right",
  },
  cupsAhorroPct: {
    fontSize: 6.5,
    color: BRAND.gris,
    textAlign: "right",
    marginTop: 1,
  },
  cupsListTotalRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    paddingTop: 6,
    paddingHorizontal: 6,
    borderTopWidth: 1,
    borderTopColor: BRAND.azul,
  },
  cupsListTotalLabel: {
    fontSize: 8,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.azul,
  },
  cupsListTotalValue: {
    fontSize: 11,
    fontFamily: PDF_FONT_DISPLAY,
    fontWeight: "bold",
    color: BRAND.verde,
    textAlign: "right",
  },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 32,
    right: 32,
    borderTopWidth: 0.5,
    borderTopColor: BRAND.borde,
    paddingTop: 6,
  },
  footerText: {
    fontSize: 6.5,
    color: BRAND.gris,
    lineHeight: 1.35,
    textAlign: "center",
  },
})
