import { normalizeIncidenciaTicket } from '@/lib/incidencias';

type IncidenciaSeedInput = Parameters<typeof normalizeIncidenciaTicket>[0];

export const INCIDENCIAS_SEED: IncidenciaSeedInput[] = [
  {
    id: 'inc-1',
    clientName: 'Residencia Geriátrica Verde',
    tipo: 'Retraso de Firma',
    prioridad: 'alta',
    estado: 'pendiente',
    comercialId: 'staff-marta',
    comercialName: 'Marta Rivas',
    descripcion: 'Cliente renegociando penalización con comercializadora saliente',
    createdAt: '2026-05-20',
    origen: 'comercial',
    canal: 'Canal Norte',
  },
  {
    id: 'inc-2',
    clientName: 'Restaurante El Laurel',
    tipo: 'Error de CUPS',
    prioridad: 'media',
    estado: 'resuelta',
    comercialId: 'staff-marta',
    comercialName: 'Marta Rivas',
    descripcion: 'El CUPS suministrado correspondía a la luz en lugar del gas. Subsanado.',
    createdAt: '2026-05-10',
    estadoAt: '2026-05-28T10:00:00.000Z',
    origen: 'sistema',
    asignadoA: 'staff-carlos',
  },
  {
    id: 'inc-3',
    clientName: 'GEA CATERING, S.L.',
    tipo: 'Tarifa Incorrecta',
    prioridad: 'critica',
    estado: 'pendiente',
    comercialId: 'staff-ignacio',
    comercialName: 'Ignacio Ortiz',
    descripcion: 'Facturación con tarifa distinta a la contratada en alta.',
    createdAt: '2026-05-22',
    origen: 'cliente',
    canal: 'Web cliente',
  },
  {
    id: 'inc-4',
    clientName: 'ANA MARIA PINEDA BARRAGA',
    tipo: 'Incidencia Cartera',
    prioridad: 'baja',
    estado: 'cancelada',
    comercialId: 'staff-ignacio',
    comercialName: 'Ignacio Ortiz',
    descripcion: 'Cliente desistió del cambio de comercializadora.',
    createdAt: '2026-05-18',
    estadoAt: '2026-05-28T14:00:00.000Z',
    origen: 'manual',
    asignadoA: 'staff-ignacio',
  },
  {
    id: 'inc-5',
    clientName: 'Hotel Continental',
    tipo: 'Reclamación Distribuidora',
    prioridad: 'baja',
    estado: 'resuelta',
    comercialId: 'staff-marta',
    comercialName: 'Marta Rivas',
    descripcion: 'Corte de suministro revertido tras reclamación.',
    createdAt: '2026-04-01',
    estadoAt: '2026-05-15T08:00:00.000Z',
    origen: 'comercial',
    asignadoA: 'staff-carlos',
  },
  {
    id: 'inc-6',
    clientName: 'Taller Mecánico Sur',
    tipo: 'Retraso de Firma',
    prioridad: 'media',
    estado: 'cancelada',
    comercialId: 'staff-ignacio',
    comercialName: 'Ignacio Ortiz',
    descripcion: 'Alta anulada por falta de documentación.',
    createdAt: '2026-04-10',
    estadoAt: '2026-05-10T09:00:00.000Z',
    origen: 'sistema',
  },
  {
    id: 'inc-7',
    clientName: 'Panadería La Espiga',
    tipo: 'Incidencia Cartera',
    estado: 'sin_categorizar',
    comercialId: 'staff-marta',
    comercialName: 'Marta Rivas',
    descripcion: 'Ticket recién creado sin clasificar.',
    createdAt: '2026-06-10',
    origen: 'manual',
    codigo: 'INC-0007',
  },
  {
    id: 'inc-8',
    clientName: 'Clínica Dental Sol',
    tipo: 'Tarifa Incorrecta',
    prioridad: 'alta',
    estado: 'en_progreso',
    comercialId: 'staff-ignacio',
    comercialName: 'Ignacio Ortiz',
    descripcion: 'Revisión de tarifa con comercializadora en curso.',
    createdAt: '2026-06-01',
    origen: 'comercial',
    asignadoA: 'staff-carlos',
    codigo: 'INC-0008',
  },
];
