import type { WebLead } from "../ventas/web-leads"

const now = Date.now()

export const DEMO_WEB_LEADS: WebLead[] = [
  {
    id: "demo-web-lead-1",
    createdAt: new Date(now - 45 * 60_000).toISOString(),
    updatedAt: new Date(now - 45 * 60_000).toISOString(),
    nombre: "María García López",
    telefono: "+34 612 345 678",
    email: "maria.garcia@example.com",
    leadSource: "comparador",
    facturasUrls: ["https://example.com/factura-demo.pdf"],
    cups: "ES0021000000000001AB",
    currentCompany: "Iberdrola",
    currentTariffType: "2.0TD",
    estimatedSavingMonthlyEur: 32.5,
    estimatedSavingPercentage: 18,
    city: "Valencia",
    zipCode: "46001",
    fromWeb: true,
    erpPriority: 10,
    slaDueAt: new Date(now + 75 * 60_000).toISOString(),
  },
  {
    id: "demo-web-lead-2",
    createdAt: new Date(now - 130 * 60_000).toISOString(),
    updatedAt: new Date(now - 10 * 60_000).toISOString(),
    nombre: "Restaurante El Olivo",
    telefono: "+34 698 112 233",
    leadSource: "contacto",
    facturasUrls: [],
    currentCompany: "Endesa",
    estimatedSavingMonthlyEur: 89,
    city: "Madrid",
    fromWeb: true,
    erpPriority: 10,
    assignedComercialId: "com-001",
    assignedAt: new Date(now - 20 * 60_000).toISOString(),
    slaDueAt: new Date(now - 10 * 60_000).toISOString(),
    resubmittedAt: new Date(now - 10 * 60_000).toISOString(),
  },
  {
    id: "demo-web-lead-3",
    createdAt: new Date(now - 20 * 60_000).toISOString(),
    updatedAt: new Date(now - 20 * 60_000).toISOString(),
    nombre: "Pedro Sánchez",
    telefono: "+34 655 443 322",
    email: "pedro.s@example.com",
    leadSource: "factura",
    facturasUrls: ["https://example.com/factura-2.pdf"],
    estimatedSavingMonthlyEur: 15.2,
    estimatedSavingPercentage: 12,
    fromWeb: true,
    erpPriority: 10,
    slaDueAt: new Date(now + 100 * 60_000).toISOString(),
  },
]
